language: perl
addons:
  apt:
    packages:
    - git
    - libyaml-dev
    - libmysqlclient-dev
perl:
  - 5.14
sudo: required
dist: precise
install:
  - "source ./install_dependencies.sh"
script: dzil test	
